logo: assets/hex_logo.png
theme: jekyll-theme-minimal
color-scheme: light
plugins:
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
